# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/EEG_cal.srcs/sources_1/ip/fifo_mean/fifo_mean.xci
# IP: The module: 'fifo_mean' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/EEG_cal.srcs/sources_1/ip/fifo_mean/fifo_mean.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_mean'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/EEG_cal.srcs/sources_1/ip/fifo_mean/fifo_mean_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_mean'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/EEG_cal.srcs/sources_1/ip/fifo_mean/fifo_mean.xci
# IP: The module: 'fifo_mean' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/EEG_cal.srcs/sources_1/ip/fifo_mean/fifo_mean.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_mean'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/EEG_cal.srcs/sources_1/ip/fifo_mean/fifo_mean_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_mean'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
