# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config  -id {Synth 8-4446}  -string {{WARNING: [Synth 8-4446] all outputs are unconnected for this instance and logic may be removed [C:/Users/ALIENTEK/Desktop/N7020/28_top_cymometer/rtl/top_cymometer.v:83]}}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {Constraints 18-619}  -string {{WARNING: [Constraints 18-619] A clock with name 'sys_clk' already exists, overwriting the previous clock with the same name. [C:/Users/ALIENTEK/Desktop/N7020/28_top_cymometer/prj/top_cymometer.srcs/constrs_1/new/pin.xdc:2]}}  -suppress 
set_msg_config  -id {Common 17-576}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'i2c_ack' of module 'i2c_dri' is unconnected for instance 'u_i2c_dri' [H:/ZEYI/FPGA/K7/K410T/Finalized/ov5640_lcd/rtl/ov5640_dri.v:103]}}  -suppress 
set_msg_config  -id {Synth 8-7023}  -string {{WARNING: [Synth 8-7023] instance 'u_i2c_dri' of module 'i2c_dri' has 13 connections declared, but only 12 given [H:/ZEYI/FPGA/K7/K410T/Finalized/ov5640_lcd/rtl/ov5640_dri.v:103]}}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 

start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  create_project -in_memory -part xc7k325tffg900-2
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir D:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/EEG_cal.cache/wt [current_project]
  set_property parent.project_path D:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/EEG_cal.xpr [current_project]
  set_property ip_output_repo D:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/EEG_cal.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  add_files -quiet D:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/EEG_cal.runs/synth_1/MAND.dcp
  read_xdc D:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/EEG_cal.srcs/constrs_1/new/ip_clk_wiz.xdc
  link_design -top MAND -part xc7k325tffg900-2
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force MAND_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file MAND_drc_opted.rpt -pb MAND_drc_opted.pb -rpx MAND_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design 
  write_checkpoint -force MAND_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file MAND_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file MAND_utilization_placed.rpt -pb MAND_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file MAND_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force MAND_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file MAND_drc_routed.rpt -pb MAND_drc_routed.pb -rpx MAND_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file MAND_methodology_drc_routed.rpt -pb MAND_methodology_drc_routed.pb -rpx MAND_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file MAND_power_routed.rpt -pb MAND_power_summary_routed.pb -rpx MAND_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file MAND_route_status.rpt -pb MAND_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file MAND_timing_summary_routed.rpt -pb MAND_timing_summary_routed.pb -rpx MAND_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file MAND_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file MAND_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file MAND_bus_skew_routed.rpt -pb MAND_bus_skew_routed.pb -rpx MAND_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force MAND_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

