# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config  -id {Synth 8-4446}  -string {{WARNING: [Synth 8-4446] all outputs are unconnected for this instance and logic may be removed [C:/Users/ALIENTEK/Desktop/N7020/28_top_cymometer/rtl/top_cymometer.v:83]}}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {Constraints 18-619}  -string {{WARNING: [Constraints 18-619] A clock with name 'sys_clk' already exists, overwriting the previous clock with the same name. [C:/Users/ALIENTEK/Desktop/N7020/28_top_cymometer/prj/top_cymometer.srcs/constrs_1/new/pin.xdc:2]}}  -suppress 
set_msg_config  -id {Common 17-576}  -suppress 
set_msg_config  -id {Synth 8-7071}  -string {{WARNING: [Synth 8-7071] port 'i2c_ack' of module 'i2c_dri' is unconnected for instance 'u_i2c_dri' [H:/ZEYI/FPGA/K7/K410T/Finalized/ov5640_lcd/rtl/ov5640_dri.v:103]}}  -suppress 
set_msg_config  -id {Synth 8-7023}  -string {{WARNING: [Synth 8-7023] instance 'u_i2c_dri' of module 'i2c_dri' has 13 connections declared, but only 12 given [H:/ZEYI/FPGA/K7/K410T/Finalized/ov5640_lcd/rtl/ov5640_dri.v:103]}}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/EEG_cal.cache/wt [current_project]
set_property parent.project_path D:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/EEG_cal.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/EEG_cal.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/code/mean_cal_new.v
  D:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/code/MAND.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/EEG_cal.srcs/constrs_1/new/ip_clk_wiz.xdc
set_property used_in_implementation false [get_files D:/YCB/YCB/PROJECT/EEG_signal_processing/FPGA/EEG_cal/EEG_cal.srcs/constrs_1/new/ip_clk_wiz.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top MAND -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MAND.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MAND_utilization_synth.rpt -pb MAND_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
